#!/usr/bin/env bash --login
# The --login is so RVM works

# Rebuild the project
rake bower:vendor

# This script is the general steps to go from a bare Rails project to one with Gentelella plus Devise talking to a SQLite database

pushd ..

TEST_DIR=gentelella-rails-devise-test
RUBY=ruby-2.3.1

if [ -d $TEST_DIR ]; then
    rm -rf $TEST_DIR
fi

rvm use $RUBY

rails new $TEST_DIR --skip-bundle

cd $TEST_DIR
echo $RUBY > .ruby-version

echo "gem 'gentelella-rails', path: '../gentelella-rails'" >>Gemfile
echo "gem 'devise'" >>Gemfile # Devise gem must be installed in Gemfile before running generator

bundle install --local

#rails generate devise:install
rails generate gentelella:install --force
rails generate gentelella:install_devise --force

#rails generate devise User
rake db:create
rake db:migrate
rake db:seed

# Remove last line from development.rb file which should be "end" and add new config statements
sed -i -e '$d' config/environments/development.rb
echo "config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }" >> config/environments/development.rb
echo "end" >> config/environments/development.rb

echo
echo "======================================================"
echo "The sample user is admin@example.com password admin123"
echo "======================================================"
echo

rails s
